{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Transformer\n",
    "*Transformer network with Multi-Head Attention*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from chatbot.transformer import Transformer\n",
    "# import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# df = pd.read_csv('../data/translation/dataset.csv', sep=';')\n",
    "tf = Transformer(lang='en-us', num_epoch=100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data loaded with hyperparams: Corpus(lang='en-us', max_length=15, batch_size=64, buffer_size=20000, _start_token=[10619], _end_token=[10620], _vocab_size=10621).\n",
      "<keras.engine.functional.Functional object at 0x000001A1EF1387C0> compiled successfully.\n",
      "Epoch 1/100\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "in user code:\n\n    File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function  *\n        return step_function(self, iterator)\n    File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 181, in _count_f1  *\n        with tf.compat.v1.Session() as sess:  print(y_pred.eval())\n\n    InvalidArgumentError: Graph execution error:\n    \n    Detected at node 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource' defined at (most recent call last):\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 196, in _run_module_as_main\n          return _run_code(code, main_globals, None,\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 86, in _run_code\n          exec(code, run_globals)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n          app.launch_new_instance()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n          app.start()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n          self.io_loop.start()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n          self.asyncio_loop.run_forever()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n          self._run_once()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n          handle._run()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\events.py\", line 80, in _run\n          self._context.run(self._callback, *self._args)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n          await self.process_one()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n          await dispatch(*args)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n          await result\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n          reply_content = await reply_content\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n          res = shell.run_cell(\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n          return super().run_cell(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in run_cell\n          result = self._run_cell(\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2995, in _run_cell\n          return runner(coro)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n          coro.send(None)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3194, in run_cell_async\n          has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3373, in run_ast_nodes\n          if await self.run_code(code, result, async_=asy):\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n          exec(code_obj, self.user_global_ns, self.user_ns)\n        File \"C:\\Users\\zer0deck\\AppData\\Local\\Temp\\ipykernel_25468\\2216969438.py\", line 1, in <module>\n          tf.fit(path='data/conv-ai-2017')\n        File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 297, in fit\n          self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n          tmp_logs = self.train_function(iterator)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n          return step_function(self, iterator)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n          outputs = model.distribute_strategy.run(run_step, args=(data,))\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n          outputs = model.train_step(data)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n          y_pred = self(x, training=True)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n          return super().__call__(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n          return self._run_internal_graph(inputs, training=training, mask=mask)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n          outputs = node.layer(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n          return super().__call__(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n          return self._run_internal_graph(inputs, training=training, mask=mask)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n          outputs = node.layer(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n          return super().__call__(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n          return self._run_internal_graph(inputs, training=training, mask=mask)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n          outputs = node.layer(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 81, in call\n          query = self.query_dense(query)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\layers\\core\\dense.py\", line 244, in call\n          outputs = tf.tensordot(inputs, self.kernel, [[rank - 1], [0]])\n    Node: 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource'\n    Detected at node 'iterator' defined at (most recent call last):\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 196, in _run_module_as_main\n          return _run_code(code, main_globals, None,\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 86, in _run_code\n          exec(code, run_globals)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n          app.launch_new_instance()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n          app.start()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n          self.io_loop.start()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n          self.asyncio_loop.run_forever()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n          self._run_once()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n          handle._run()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\events.py\", line 80, in _run\n          self._context.run(self._callback, *self._args)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n          await self.process_one()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n          await dispatch(*args)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n          await result\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n          reply_content = await reply_content\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n          res = shell.run_cell(\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n          return super().run_cell(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in run_cell\n          result = self._run_cell(\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2995, in _run_cell\n          return runner(coro)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n          coro.send(None)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3194, in run_cell_async\n          has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3373, in run_ast_nodes\n          if await self.run_code(code, result, async_=asy):\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n          exec(code_obj, self.user_global_ns, self.user_ns)\n        File \"C:\\Users\\zer0deck\\AppData\\Local\\Temp\\ipykernel_25468\\2216969438.py\", line 1, in <module>\n          tf.fit(path='data/conv-ai-2017')\n        File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 297, in fit\n          self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n          tmp_logs = self.train_function(iterator)\n    Node: 'iterator'\n    2 root error(s) found.\n      (0) INVALID_ARGUMENT: You must feed a value for placeholder tensor 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource' with dtype resource\n    \t [[{{node transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource}}]]\n      (1) INVALID_ARGUMENT: You must feed a value for placeholder tensor 'iterator' with dtype resource\n    \t [[{{node iterator}}]]\n    0 successful operations.\n    0 derived errors ignored.\n    \n    Original stack trace for 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource':\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 196, in _run_module_as_main\n        return _run_code(code, main_globals, None,\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 86, in _run_code\n        exec(code, run_globals)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n        app.launch_new_instance()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n        app.start()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n        self.io_loop.start()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n        self.asyncio_loop.run_forever()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n        self._run_once()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n        handle._run()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\events.py\", line 80, in _run\n        self._context.run(self._callback, *self._args)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n        await self.process_one()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n        await dispatch(*args)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n        await result\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n        reply_content = await reply_content\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n        res = shell.run_cell(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n        return super().run_cell(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in run_cell\n        result = self._run_cell(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2995, in _run_cell\n        return runner(coro)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n        coro.send(None)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3194, in run_cell_async\n        has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3373, in run_ast_nodes\n        if await self.run_code(code, result, async_=asy):\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n        exec(code_obj, self.user_global_ns, self.user_ns)\n      File \"C:\\Users\\zer0deck\\AppData\\Local\\Temp\\ipykernel_25468\\2216969438.py\", line 1, in <module>\n        tf.fit(path='data/conv-ai-2017')\n      File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 297, in fit\n        self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n        tmp_logs = self.train_function(iterator)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 915, in __call__\n        result = self._call(*args, **kwds)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 963, in _call\n        self._initialize(args, kwds, add_initializers_to=initializers)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 785, in _initialize\n        self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2523, in _get_concrete_function_internal_garbage_collected\n        graph_function, _ = self._maybe_define_function(args, kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2760, in _maybe_define_function\n        graph_function = self._create_graph_function(args, kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2670, in _create_graph_function\n        func_graph_module.func_graph_from_py_func(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1247, in func_graph_from_py_func\n        func_outputs = python_func(*func_args, **func_kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 677, in wrapped_fn\n        out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1222, in autograph_handler\n        return autograph.converted_call(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n        return step_function(self, iterator)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 1315, in run\n        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 2891, in call_for_each_replica\n        return self._call_for_each_replica(fn, args, kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 3692, in _call_for_each_replica\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n        outputs = model.train_step(data)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n        y_pred = self(x, training=True)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n        return super().__call__(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n        return self._run_internal_graph(inputs, training=training, mask=mask)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n        outputs = node.layer(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n        return super().__call__(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n        return self._run_internal_graph(inputs, training=training, mask=mask)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n        outputs = node.layer(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n        return super().__call__(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n        return self._run_internal_graph(inputs, training=training, mask=mask)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n        outputs = node.layer(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 81, in call\n        query = self.query_dense(query)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\layers\\core\\dense.py\", line 244, in call\n        outputs = tf.tensordot(inputs, self.kernel, [[rank - 1], [0]])\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 1176, in op_dispatch_handler\n        return dispatch_target(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 5120, in tensordot\n        b = ops.convert_to_tensor(b, name=\"b\")\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\profiler\\trace.py\", line 183, in wrapped\n        return func(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1638, in convert_to_tensor\n        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 2105, in _dense_var_to_tensor\n        return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 1467, in _dense_var_to_tensor\n        return self.value()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 582, in value\n        return self._read_variable_op()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 704, in _read_variable_op\n        result = read_and_set_handle(no_copy)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 694, in read_and_set_handle\n        result = gen_resource_variable_ops.read_variable_op(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\gen_resource_variable_ops.py\", line 538, in read_variable_op\n        _, _, _op, _outputs = _op_def_library._apply_op_helper(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 779, in _apply_op_helper\n        _ExtractInputsAndAttrs(op_type_name, op_def, allowed_list_attr_map,\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 552, in _ExtractInputsAndAttrs\n        values = ops.convert_to_tensor(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\profiler\\trace.py\", line 183, in wrapped\n        return func(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1593, in convert_to_tensor\n        return graph.capture(value, name=name)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 771, in capture\n        return self._capture_helper(tensor, name, shape)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 806, in _capture_helper\n        placeholder = _create_substitute_placeholder(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1420, in _create_substitute_placeholder\n        placeholder = graph_placeholder(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\graph_only_ops.py\", line 34, in graph_placeholder\n        op = g._create_op_internal(  # pylint: disable=protected-access\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 735, in _create_op_internal\n        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3800, in _create_op_internal\n        ret = Operation(\n    \n\n\nOriginal stack trace for 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource':\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n    app.launch_new_instance()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n    app.start()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n    self.io_loop.start()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n    self.asyncio_loop.run_forever()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n    handle._run()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n    await self.process_one()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n    await dispatch(*args)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n    await result\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n    reply_content = await reply_content\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n    res = shell.run_cell(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n    return super().run_cell(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in run_cell\n    result = self._run_cell(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2995, in _run_cell\n    return runner(coro)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n    coro.send(None)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3194, in run_cell_async\n    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3373, in run_ast_nodes\n    if await self.run_code(code, result, async_=asy):\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"C:\\Users\\zer0deck\\AppData\\Local\\Temp\\ipykernel_25468\\2216969438.py\", line 1, in <module>\n    tf.fit(path='data/conv-ai-2017')\n  File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 297, in fit\n    self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n    tmp_logs = self.train_function(iterator)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 915, in __call__\n    result = self._call(*args, **kwds)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 963, in _call\n    self._initialize(args, kwds, add_initializers_to=initializers)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 785, in _initialize\n    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2523, in _get_concrete_function_internal_garbage_collected\n    graph_function, _ = self._maybe_define_function(args, kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2760, in _maybe_define_function\n    graph_function = self._create_graph_function(args, kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2670, in _create_graph_function\n    func_graph_module.func_graph_from_py_func(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1247, in func_graph_from_py_func\n    func_outputs = python_func(*func_args, **func_kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 677, in wrapped_fn\n    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1222, in autograph_handler\n    return autograph.converted_call(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n    return step_function(self, iterator)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n    outputs = model.distribute_strategy.run(run_step, args=(data,))\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 1315, in run\n    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 2891, in call_for_each_replica\n    return self._call_for_each_replica(fn, args, kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 3692, in _call_for_each_replica\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n    outputs = model.train_step(data)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n    y_pred = self(x, training=True)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n    return super().__call__(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n    return self._run_internal_graph(inputs, training=training, mask=mask)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n    outputs = node.layer(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n    return super().__call__(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n    return self._run_internal_graph(inputs, training=training, mask=mask)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n    outputs = node.layer(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n    return super().__call__(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n    return self._run_internal_graph(inputs, training=training, mask=mask)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n    outputs = node.layer(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 81, in call\n    query = self.query_dense(query)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\layers\\core\\dense.py\", line 244, in call\n    outputs = tf.tensordot(inputs, self.kernel, [[rank - 1], [0]])\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 1176, in op_dispatch_handler\n    return dispatch_target(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 5120, in tensordot\n    b = ops.convert_to_tensor(b, name=\"b\")\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\profiler\\trace.py\", line 183, in wrapped\n    return func(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1638, in convert_to_tensor\n    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 2105, in _dense_var_to_tensor\n    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 1467, in _dense_var_to_tensor\n    return self.value()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 582, in value\n    return self._read_variable_op()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 704, in _read_variable_op\n    result = read_and_set_handle(no_copy)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 694, in read_and_set_handle\n    result = gen_resource_variable_ops.read_variable_op(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\gen_resource_variable_ops.py\", line 538, in read_variable_op\n    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 779, in _apply_op_helper\n    _ExtractInputsAndAttrs(op_type_name, op_def, allowed_list_attr_map,\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 552, in _ExtractInputsAndAttrs\n    values = ops.convert_to_tensor(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\profiler\\trace.py\", line 183, in wrapped\n    return func(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1593, in convert_to_tensor\n    return graph.capture(value, name=name)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 771, in capture\n    return self._capture_helper(tensor, name, shape)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 806, in _capture_helper\n    placeholder = _create_substitute_placeholder(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1420, in _create_substitute_placeholder\n    placeholder = graph_placeholder(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\graph_only_ops.py\", line 34, in graph_placeholder\n    op = g._create_op_internal(  # pylint: disable=protected-access\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 735, in _create_op_internal\n    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3800, in _create_op_internal\n    ret = Operation(\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [3], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mtf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpath\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mdata/conv-ai-2017\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32md:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py:297\u001b[0m, in \u001b[0;36mTransformer.fit\u001b[1;34m(self, data, path)\u001b[0m\n\u001b[0;32m    294\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_model\u001b[39m.\u001b[39mcompile(optimizer\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_optimizer, loss\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_count_loss, metrics\u001b[39m=\u001b[39m[\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_count_accuracy, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_count_f1])\n\u001b[0;32m    296\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_model\u001b[39m}\u001b[39;00m\u001b[39m compiled successfully.\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m--> 297\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_model\u001b[39m.\u001b[39;49mfit(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_data_controller\u001b[39m.\u001b[39;49mdataset, epochs\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mnum_epoch)\n",
      "File \u001b[1;32mc:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[0;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[1;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[0;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32mc:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py:1233\u001b[0m, in \u001b[0;36mfunc_graph_from_py_func.<locals>.autograph_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m   1231\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:  \u001b[39m# pylint:disable=broad-except\u001b[39;00m\n\u001b[0;32m   1232\u001b[0m   \u001b[39mif\u001b[39;00m \u001b[39mhasattr\u001b[39m(e, \u001b[39m\"\u001b[39m\u001b[39mag_error_metadata\u001b[39m\u001b[39m\"\u001b[39m):\n\u001b[1;32m-> 1233\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mag_error_metadata\u001b[39m.\u001b[39mto_exception(e)\n\u001b[0;32m   1234\u001b[0m   \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   1235\u001b[0m     \u001b[39mraise\u001b[39;00m\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m: in user code:\n\n    File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function  *\n        return step_function(self, iterator)\n    File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 181, in _count_f1  *\n        with tf.compat.v1.Session() as sess:  print(y_pred.eval())\n\n    InvalidArgumentError: Graph execution error:\n    \n    Detected at node 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource' defined at (most recent call last):\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 196, in _run_module_as_main\n          return _run_code(code, main_globals, None,\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 86, in _run_code\n          exec(code, run_globals)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n          app.launch_new_instance()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n          app.start()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n          self.io_loop.start()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n          self.asyncio_loop.run_forever()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n          self._run_once()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n          handle._run()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\events.py\", line 80, in _run\n          self._context.run(self._callback, *self._args)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n          await self.process_one()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n          await dispatch(*args)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n          await result\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n          reply_content = await reply_content\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n          res = shell.run_cell(\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n          return super().run_cell(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in run_cell\n          result = self._run_cell(\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2995, in _run_cell\n          return runner(coro)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n          coro.send(None)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3194, in run_cell_async\n          has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3373, in run_ast_nodes\n          if await self.run_code(code, result, async_=asy):\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n          exec(code_obj, self.user_global_ns, self.user_ns)\n        File \"C:\\Users\\zer0deck\\AppData\\Local\\Temp\\ipykernel_25468\\2216969438.py\", line 1, in <module>\n          tf.fit(path='data/conv-ai-2017')\n        File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 297, in fit\n          self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n          tmp_logs = self.train_function(iterator)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n          return step_function(self, iterator)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n          outputs = model.distribute_strategy.run(run_step, args=(data,))\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n          outputs = model.train_step(data)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n          y_pred = self(x, training=True)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n          return super().__call__(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n          return self._run_internal_graph(inputs, training=training, mask=mask)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n          outputs = node.layer(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n          return super().__call__(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n          return self._run_internal_graph(inputs, training=training, mask=mask)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n          outputs = node.layer(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n          return super().__call__(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n          return self._run_internal_graph(inputs, training=training, mask=mask)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n          outputs = node.layer(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 81, in call\n          query = self.query_dense(query)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n          outputs = call_fn(inputs, *args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\layers\\core\\dense.py\", line 244, in call\n          outputs = tf.tensordot(inputs, self.kernel, [[rank - 1], [0]])\n    Node: 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource'\n    Detected at node 'iterator' defined at (most recent call last):\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 196, in _run_module_as_main\n          return _run_code(code, main_globals, None,\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 86, in _run_code\n          exec(code, run_globals)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n          app.launch_new_instance()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n          app.start()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n          self.io_loop.start()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n          self.asyncio_loop.run_forever()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n          self._run_once()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n          handle._run()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\events.py\", line 80, in _run\n          self._context.run(self._callback, *self._args)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n          await self.process_one()\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n          await dispatch(*args)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n          await result\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n          reply_content = await reply_content\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n          res = shell.run_cell(\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n          return super().run_cell(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in run_cell\n          result = self._run_cell(\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2995, in _run_cell\n          return runner(coro)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n          coro.send(None)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3194, in run_cell_async\n          has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3373, in run_ast_nodes\n          if await self.run_code(code, result, async_=asy):\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n          exec(code_obj, self.user_global_ns, self.user_ns)\n        File \"C:\\Users\\zer0deck\\AppData\\Local\\Temp\\ipykernel_25468\\2216969438.py\", line 1, in <module>\n          tf.fit(path='data/conv-ai-2017')\n        File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 297, in fit\n          self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n          return fn(*args, **kwargs)\n        File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n          tmp_logs = self.train_function(iterator)\n    Node: 'iterator'\n    2 root error(s) found.\n      (0) INVALID_ARGUMENT: You must feed a value for placeholder tensor 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource' with dtype resource\n    \t [[{{node transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource}}]]\n      (1) INVALID_ARGUMENT: You must feed a value for placeholder tensor 'iterator' with dtype resource\n    \t [[{{node iterator}}]]\n    0 successful operations.\n    0 derived errors ignored.\n    \n    Original stack trace for 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource':\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 196, in _run_module_as_main\n        return _run_code(code, main_globals, None,\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 86, in _run_code\n        exec(code, run_globals)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n        app.launch_new_instance()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n        app.start()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n        self.io_loop.start()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n        self.asyncio_loop.run_forever()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n        self._run_once()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n        handle._run()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\events.py\", line 80, in _run\n        self._context.run(self._callback, *self._args)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n        await self.process_one()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n        await dispatch(*args)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n        await result\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n        reply_content = await reply_content\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n        res = shell.run_cell(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n        return super().run_cell(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in run_cell\n        result = self._run_cell(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2995, in _run_cell\n        return runner(coro)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n        coro.send(None)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3194, in run_cell_async\n        has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3373, in run_ast_nodes\n        if await self.run_code(code, result, async_=asy):\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n        exec(code_obj, self.user_global_ns, self.user_ns)\n      File \"C:\\Users\\zer0deck\\AppData\\Local\\Temp\\ipykernel_25468\\2216969438.py\", line 1, in <module>\n        tf.fit(path='data/conv-ai-2017')\n      File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 297, in fit\n        self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n        tmp_logs = self.train_function(iterator)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 915, in __call__\n        result = self._call(*args, **kwds)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 963, in _call\n        self._initialize(args, kwds, add_initializers_to=initializers)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 785, in _initialize\n        self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2523, in _get_concrete_function_internal_garbage_collected\n        graph_function, _ = self._maybe_define_function(args, kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2760, in _maybe_define_function\n        graph_function = self._create_graph_function(args, kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2670, in _create_graph_function\n        func_graph_module.func_graph_from_py_func(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1247, in func_graph_from_py_func\n        func_outputs = python_func(*func_args, **func_kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 677, in wrapped_fn\n        out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1222, in autograph_handler\n        return autograph.converted_call(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n        return step_function(self, iterator)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 1315, in run\n        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 2891, in call_for_each_replica\n        return self._call_for_each_replica(fn, args, kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 3692, in _call_for_each_replica\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n        outputs = model.train_step(data)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n        y_pred = self(x, training=True)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n        return super().__call__(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n        return self._run_internal_graph(inputs, training=training, mask=mask)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n        outputs = node.layer(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n        return super().__call__(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n        return self._run_internal_graph(inputs, training=training, mask=mask)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n        outputs = node.layer(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n        return super().__call__(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n        return self._run_internal_graph(inputs, training=training, mask=mask)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n        outputs = node.layer(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 81, in call\n        query = self.query_dense(query)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n        outputs = call_fn(inputs, *args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\layers\\core\\dense.py\", line 244, in call\n        outputs = tf.tensordot(inputs, self.kernel, [[rank - 1], [0]])\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n        return fn(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 1176, in op_dispatch_handler\n        return dispatch_target(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 5120, in tensordot\n        b = ops.convert_to_tensor(b, name=\"b\")\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\profiler\\trace.py\", line 183, in wrapped\n        return func(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1638, in convert_to_tensor\n        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 2105, in _dense_var_to_tensor\n        return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 1467, in _dense_var_to_tensor\n        return self.value()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 582, in value\n        return self._read_variable_op()\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 704, in _read_variable_op\n        result = read_and_set_handle(no_copy)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 694, in read_and_set_handle\n        result = gen_resource_variable_ops.read_variable_op(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\gen_resource_variable_ops.py\", line 538, in read_variable_op\n        _, _, _op, _outputs = _op_def_library._apply_op_helper(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 779, in _apply_op_helper\n        _ExtractInputsAndAttrs(op_type_name, op_def, allowed_list_attr_map,\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 552, in _ExtractInputsAndAttrs\n        values = ops.convert_to_tensor(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\profiler\\trace.py\", line 183, in wrapped\n        return func(*args, **kwargs)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1593, in convert_to_tensor\n        return graph.capture(value, name=name)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 771, in capture\n        return self._capture_helper(tensor, name, shape)\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 806, in _capture_helper\n        placeholder = _create_substitute_placeholder(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1420, in _create_substitute_placeholder\n        placeholder = graph_placeholder(\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\graph_only_ops.py\", line 34, in graph_placeholder\n        op = g._create_op_internal(  # pylint: disable=protected-access\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 735, in _create_op_internal\n        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access\n      File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3800, in _create_op_internal\n        ret = Operation(\n    \n\n\nOriginal stack trace for 'transformer/decoder/decoder_layer_0/attention_1/dense_36/Tensordot/ReadVariableOp/resource':\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n    app.launch_new_instance()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n    app.start()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n    self.io_loop.start()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n    self.asyncio_loop.run_forever()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\base_events.py\", line 1899, in _run_once\n    handle._run()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n    await self.process_one()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n    await dispatch(*args)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n    await result\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n    reply_content = await reply_content\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n    res = shell.run_cell(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n    return super().run_cell(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in run_cell\n    result = self._run_cell(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2995, in _run_cell\n    return runner(coro)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n    coro.send(None)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3194, in run_cell_async\n    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3373, in run_ast_nodes\n    if await self.run_code(code, result, async_=asy):\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3433, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"C:\\Users\\zer0deck\\AppData\\Local\\Temp\\ipykernel_25468\\2216969438.py\", line 1, in <module>\n    tf.fit(path='data/conv-ai-2017')\n  File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 297, in fit\n    self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n    tmp_logs = self.train_function(iterator)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 915, in __call__\n    result = self._call(*args, **kwds)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 963, in _call\n    self._initialize(args, kwds, add_initializers_to=initializers)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 785, in _initialize\n    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2523, in _get_concrete_function_internal_garbage_collected\n    graph_function, _ = self._maybe_define_function(args, kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2760, in _maybe_define_function\n    graph_function = self._create_graph_function(args, kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 2670, in _create_graph_function\n    func_graph_module.func_graph_from_py_func(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1247, in func_graph_from_py_func\n    func_outputs = python_func(*func_args, **func_kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 677, in wrapped_fn\n    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1222, in autograph_handler\n    return autograph.converted_call(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n    return step_function(self, iterator)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n    outputs = model.distribute_strategy.run(run_step, args=(data,))\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 1315, in run\n    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 2891, in call_for_each_replica\n    return self._call_for_each_replica(fn, args, kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 3692, in _call_for_each_replica\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n    outputs = model.train_step(data)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n    y_pred = self(x, training=True)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n    return super().__call__(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n    return self._run_internal_graph(inputs, training=training, mask=mask)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n    outputs = node.layer(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n    return super().__call__(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n    return self._run_internal_graph(inputs, training=training, mask=mask)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n    outputs = node.layer(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n    return super().__call__(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n    return self._run_internal_graph(inputs, training=training, mask=mask)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n    outputs = node.layer(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"d:\\Users\\zer0deck\\Documents\\Work\\python\\SW\\transformer_chatbot\\chatbot\\transformer.py\", line 81, in call\n    query = self.query_dense(query)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n    outputs = call_fn(inputs, *args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\keras\\layers\\core\\dense.py\", line 244, in call\n    outputs = tf.tensordot(inputs, self.kernel, [[rank - 1], [0]])\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n    return fn(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 1176, in op_dispatch_handler\n    return dispatch_target(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 5120, in tensordot\n    b = ops.convert_to_tensor(b, name=\"b\")\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\profiler\\trace.py\", line 183, in wrapped\n    return func(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1638, in convert_to_tensor\n    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 2105, in _dense_var_to_tensor\n    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 1467, in _dense_var_to_tensor\n    return self.value()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 582, in value\n    return self._read_variable_op()\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 704, in _read_variable_op\n    result = read_and_set_handle(no_copy)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py\", line 694, in read_and_set_handle\n    result = gen_resource_variable_ops.read_variable_op(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\ops\\gen_resource_variable_ops.py\", line 538, in read_variable_op\n    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 779, in _apply_op_helper\n    _ExtractInputsAndAttrs(op_type_name, op_def, allowed_list_attr_map,\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 552, in _ExtractInputsAndAttrs\n    values = ops.convert_to_tensor(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\profiler\\trace.py\", line 183, in wrapped\n    return func(*args, **kwargs)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1593, in convert_to_tensor\n    return graph.capture(value, name=name)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 771, in capture\n    return self._capture_helper(tensor, name, shape)\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 806, in _capture_helper\n    placeholder = _create_substitute_placeholder(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1420, in _create_substitute_placeholder\n    placeholder = graph_placeholder(\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\eager\\graph_only_ops.py\", line 34, in graph_placeholder\n    op = g._create_op_internal(  # pylint: disable=protected-access\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 735, in _create_op_internal\n    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access\n  File \"c:\\ProgramData\\miniforge3\\envs\\tfenv\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3800, in _create_op_internal\n    ret = Operation(\n"
     ]
    }
   ],
   "source": [
    "tf.fit(path='data/conv-ai-2017')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "tf.save_to_folder(path='trained_models/transformer/conv-ai-2017')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# DNN\n",
    "\n",
    "*Bag-Of-Words based DNN network*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import nltk\n",
    "# from nltk.stem.lancaster import LancasterStemmer\n",
    "# import numpy as np\n",
    "# import tflearn\n",
    "# import tensorflow as tf\n",
    "# import json\n",
    "# import pickle\n",
    "# import random\n",
    "\n",
    "# nltk.download(\"punkt\")\n",
    "\n",
    "# #Loading intents.json\n",
    "# with open('intents.json') as intents:\n",
    "#   data = json.load(intents)\n",
    "\n",
    "# stemmer = LancasterStemmer()\n",
    "\n",
    "# try:\n",
    "#     with open('data.pickle','rb') as f:\n",
    "#         words, labels, training, output = pickle.load(f)\n",
    "# except:\n",
    "# # Fetching and Feeding information--\n",
    "#     words = []\n",
    "#     labels = []\n",
    "#     x_docs = []\n",
    "#     y_docs = []\n",
    "\n",
    "#     for intent in data['intents']:\n",
    "#         for pattern in intent['patterns']:\n",
    "#             wrds = nltk.word_tokenize(pattern)\n",
    "#             words.extend(wrds)\n",
    "#             x_docs.append(wrds)\n",
    "#             y_docs.append(intent['tag'])\n",
    "\n",
    "#             if intent['tag'] not in labels:\n",
    "#                 labels.append(intent['tag'])\n",
    "\n",
    "#     words = [stemmer.stem(w.lower()) for w in words if w not in \"?\"]\n",
    "#     words = sorted(list(set(words)))\n",
    "#     labels = sorted(labels)\n",
    "\n",
    "#     training = []\n",
    "#     output = []\n",
    "\n",
    "#     out_empty = [0 for _ in range(len(labels))]\n",
    "\n",
    "#     # One hot encoding, Converting the words to numerals\n",
    "#     for x, doc in enumerate(x_docs):\n",
    "#         bag = []\n",
    "#         wrds = [stemmer.stem(w) for w in doc]\n",
    "#         for w in words:\n",
    "#             if w in wrds:\n",
    "#                 bag.append(1)\n",
    "#             else:\n",
    "#                 bag.append(0)\n",
    "\n",
    "\n",
    "#         output_row = out_empty[:]\n",
    "#         output_row[labels.index(y_docs[x])] = 1\n",
    "\n",
    "#         training.append(bag)\n",
    "#         output.append(output_row)\n",
    "\n",
    "\n",
    "#     training = np.array(training)\n",
    "#     output = np.array(output)\n",
    "\n",
    "#     with open('data.pickle','wb') as f:\n",
    "#         pickle.dump((words, labels, training, output), f)\n",
    "\n",
    "\n",
    "# net = tflearn.input_data(shape=[None, len(training[0])])\n",
    "# net = tflearn.fully_connected(net, 8)\n",
    "# net = tflearn.fully_connected(net, 8)\n",
    "# net = tflearn.fully_connected(net, len(output[0]), activation='softmax')\n",
    "# net = tflearn.regression(net)\n",
    "\n",
    "# model = tflearn.DNN(net)\n",
    "\n",
    "# try:\n",
    "#     model.load(\"model.tflearn\")\n",
    "# except:\n",
    "\n",
    "#     model.fit(training, output, n_epoch=100, batch_size=8, show_metric=True)\n",
    "#     model.save('model.tflearn')\n",
    "\n",
    "\n",
    "# def bag_of_words(s, words):\n",
    "#     bag = [0 for _ in range(len(words))]\n",
    "#     s_words = nltk.word_tokenize(s)\n",
    "#     s_words = [stemmer.stem(word.lower()) for word in s_words]\n",
    "\n",
    "#     for se in s_words:\n",
    "#         for i, w in enumerate(words):\n",
    "#             if w == se:\n",
    "#                 bag[i] = 1\n",
    "\n",
    "#     return np.array(bag)\n",
    "\n",
    "\n",
    "# def chat():\n",
    "#     print(\"The bot is ready to talk!!(Type 'quit' to exit)\")\n",
    "#     while True:\n",
    "#         inp = input(\"\\nYou: \")\n",
    "#         if inp.lower() == 'quit':\n",
    "#             break\n",
    "\n",
    "#     #Porbability of correct response \n",
    "#         results = model.predict([bag_of_words(inp, words)])\n",
    "\n",
    "#     # Picking the greatest number from probability\n",
    "#         results_index = np.argmax(results)\n",
    "\n",
    "#         tag = labels[results_index]\n",
    "\n",
    "\n",
    "#         for tg in data['intents']:\n",
    "\n",
    "#             if tg['tag'] == tag:\n",
    "#                 responses = tg['responses']\n",
    "#             print(\"Bot:\" + random.choice(responses))\n",
    "\n",
    "\n",
    "# chat()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Default Sequential model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.8 ('tfenv')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "891e4fc61ac792e208938f292df2fbd7ee5dda42dce8831cfe4bd29bcfe9707e"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
